SELECT
    PID,
    NAME                                    AS PLAYLIST_NAME,
    DESCRIPTION,
    NUM_TRACKS,
    NUM_ALBUMS,
    NUM_ARTISTS,
    NUM_FOLLOWERS,
    NUM_EDITS,
    DURATION_MS,
    ROUND(DURATION_MS / 60000.0, 2)        AS DURATION_MIN,
    COLLABORATIVE,
    TO_TIMESTAMP(MODIFIED_AT)              AS MODIFIED_AT_TS
FROM SPOTIFY_DW.PUBLIC.DIM_PLAYLISTS
WHERE NUM_TRACKS >= 5
  AND NAME IS NOT NULL