SELECT
    TRACK_URI,
    TRACK_NAME,
    ALBUM_NAME,
    ALBUM_URI,
    ARTIST_URI,
    DURATION_MS,
    ROUND(DURATION_MS / 60000.0, 2) AS DURATION_MIN
FROM SPOTIFY_DW.PUBLIC.DIM_TRACKS
WHERE DURATION_MS > 0
  AND TRACK_NAME IS NOT NULL
  AND TRACK_NAME != ''